from django.urls import path
from .views import (
    vehicle_list_view,
    vehicle_create_view,
    vehicle_update_view,
    vehicle_delete_view,
    vehicle_model_list_view,
    vehicle_model_create_view,
    vehicle_model_update_view,
    vehicle_model_delete_view,
    mission_list_view,
    mission_add_view,
    mission_update_view,
    mission_delete_view,
    trip_request_create_view,
    trip_request_list_view,
    trip_request_approve_view,
    trip_request_reject_view,
    trip_request_employee_list_view,
    trip_request_edit_view,
    trip_request_delete_view,
    trip_request_log_view,
    fuel_card_list_view,
    fuel_card_create_view,
    fuel_card_update_view,
    fuel_card_delete_view,
    department_list_view,
    department_create_view,
    department_update_view,
    department_delete_view,
    vehicles_by_mission_view,
    trip_report_create_view,
    trip_request_approval_view,
    trip_report_list_view,
    trip_report_detail_view,
    trip_report_edit_view,
    driver_list_view,
    driver_create_view,
    driver_update_view,
    driver_delete_view,
    service_task_create_view,
    service_task_list_view,
    service_task_update_view,
    service_task_delete_view,
    service_task_detail_view,
    service_list_view,
    service_create_view,
    service_update_view,
    service_delete_view,
)

urlpatterns = [
    path('', vehicle_list_view, name='vehicle_list'),
    path('add/', vehicle_create_view, name='vehicle_add'),
    path('edit/<int:pk>/', vehicle_update_view, name='vehicle_edit'),
    path('delete/<int:pk>/', vehicle_delete_view, name='vehicle_delete'),
    path('models/', vehicle_model_list_view, name='vehicle_model_list'),
    path('models/add/', vehicle_model_create_view, name='vehicle_model_add'),
    path('models/edit/<int:pk>/', vehicle_model_update_view, name='vehicle_model_edit'),
    path('models/delete/<int:pk>/', vehicle_model_delete_view, name='vehicle_model_delete'),
    path('missions/', mission_list_view, name='mission_list'),
    path('missions/add/', mission_add_view, name='mission_add'),
    path('missions/edit/<int:pk>/', mission_update_view, name='mission_edit'),
    path('missions/delete/<int:pk>/', mission_delete_view, name='mission_delete'),
    path('trip-requests/', trip_request_list_view, name='trip_request_list'),
    path('trip-requests/add/', trip_request_create_view, name='trip_request_create'),
    path('trip-requests/<int:pk>/approve/', trip_request_approve_view, name='trip_request_approve'),
    path('trip-requests/<int:pk>/reject/', trip_request_reject_view, name='trip_request_reject'),
    path('trip-requests/<int:pk>/approval/', trip_request_approval_view, name='trip_request_approval'),
    path('my-trip-requests/', trip_request_employee_list_view, name='trip_request_employee_list'),
    path('my-trip-requests/<int:pk>/edit/', trip_request_edit_view, name='trip_request_edit'),
    path('my-trip-requests/<int:pk>/delete/', trip_request_delete_view, name='trip_request_delete'),
    path('trip-requests/log/', trip_request_log_view, name='trip_request_log'),
    path('fuel-cards/', fuel_card_list_view, name='fuel_card_list'),
    path('fuel-cards/add/', fuel_card_create_view, name='fuel_card_create'),
    path('fuel-cards/edit/<int:pk>/', fuel_card_update_view, name='fuel_card_edit'),
    path('fuel-cards/delete/<int:pk>/', fuel_card_delete_view, name='fuel_card_delete'),
    path('departments/', department_list_view, name='department_list'),
    path('departments/add/', department_create_view, name='department_create'),
    path('departments/edit/<int:pk>/', department_update_view, name='department_edit'),
    path('departments/delete/<int:pk>/', department_delete_view, name='department_delete'),
    path('api/vehicles-by-mission/<int:mission_id>/', vehicles_by_mission_view, name='vehicles_by_mission'),
    path('trip-reports/add/<int:trip_request_id>/', trip_report_create_view, name='trip_report_create'),
    path('trip-reports/', trip_report_list_view, name='trip_report_list'),
    path('trip-reports/<int:pk>/', trip_report_detail_view, name='trip_report_detail'),
    path('trip-reports/<int:pk>/edit/', trip_report_edit_view, name='trip_report_edit'),
    path('drivers/', driver_list_view, name='driver_list'),
    path('drivers/add/', driver_create_view, name='driver_create'),
    path('drivers/<int:pk>/edit/', driver_update_view, name='driver_update'),
    path('drivers/<int:pk>/delete/', driver_delete_view, name='driver_delete'),
    path('service-tasks/', service_task_list_view, name='service_task_list'),
    path('service-tasks/add/', service_task_create_view, name='service_task_create'),
    path('service-tasks/<int:pk>/edit/', service_task_update_view, name='service_task_update'),
    path('service-tasks/<int:pk>/delete/', service_task_delete_view, name='service_task_delete'),
    path('service-tasks/<int:pk>/', service_task_detail_view, name='service_task_detail'),
    path('services/', service_list_view, name='service_list'),
    path('services/add/', service_create_view, name='service_create'),
    path('services/<int:pk>/edit/', service_update_view, name='service_update'),
    path('services/<int:pk>/delete/', service_delete_view, name='service_delete'),
]
