# Generated by Django 5.2.1 on 2025-07-01 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='department',
        ),
        migrations.AddField(
            model_name='customuser',
            name='region',
            field=models.CharField(blank=True, choices=[('Sfax', 'Sfax'), ('Tunisia', 'Tunisia'), ('Gabes', 'Gabes'), ('Gafsa', 'Gafsa')], max_length=20, null=True),
        ),
    ]
