# Generated by Django 5.2.1 on 2025-05-25 20:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_cin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cin',
        ),
    ]
