# Generated by Django 5.2.1 on 2025-05-25 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_customuser_cin'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
