# Generated by Django 5.2.1 on 2025-06-20 18:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_alter_fuelcard_id_alter_fuelcard_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('fuel_card', models.ForeignKey(limit_choices_to={'type': 'Primary'}, on_delete=django.db.models.deletion.CASCADE, to='vehicles.fuelcard')),
            ],
        ),
    ]
