# Generated by Django 5.2.1 on 2025-06-20 19:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0003_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='fuel_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.fuelcard'),
        ),
        migrations.AlterField(
            model_name='department',
            name='fuel_card',
            field=models.ForeignKey(limit_choices_to={'type': 'Primary'}, on_delete=django.db.models.deletion.CASCADE, to='vehicles.fuelcard', unique=True),
        ),
    ]
