# Generated by Django 5.2.1 on 2025-06-21 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0004_vehicle_fuel_card_alter_department_fuel_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.department'),
        ),
    ]
