# Generated by Django 5.2.1 on 2025-06-23 22:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0005_vehicle_department'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MissionOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_going', models.DateField()),
                ('date_coming_back', models.DateField()),
                ('motif', models.TextField()),
                ('destination', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_trip', 'In Trip'), ('reported', 'Reported'), ('trip_ended', 'Trip Ended'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('fuel_used', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='mission_files/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.mission')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle')),
            ],
        ),
        migrations.AlterField(
            model_name='tripreport',
            name='trip_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='vehicles.missionorder'),
        ),
        migrations.DeleteModel(
            name='TripRequest',
        ),
    ]
