# Generated by Django 5.2.1 on 2025-06-24 09:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0006_missionorder_alter_tripreport_trip_request_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_going', models.DateField()),
                ('date_coming_back', models.DateField()),
                ('destination', models.CharField(max_length=255)),
                ('fuel_used', models.DecimalField(decimal_places=2, max_digits=6)),
                ('motif', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_trip', 'In Trip'), ('reported', 'Reported'), ('trip_ended', 'Trip Ended'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='service_order_files/')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.driver')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='vehicles.service')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
        migrations.DeleteModel(
            name='ServiceTask',
        ),
    ]
