# Generated by Django 5.2.1 on 2025-05-19 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0007_triprequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='status',
            field=models.CharField(choices=[('free', 'Free'), ('in_use', 'In Use')], default='free', max_length=10),
        ),
    ]
