# Generated by Django 5.2.1 on 2025-05-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0008_vehicle_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_trip', 'In Trip'), ('trip_ended', 'Trip Ended'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
