# Generated by Django 5.2.1 on 2025-05-22 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0011_vehicle_date_bought_vehicle_fuel_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TripReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_text', models.TextField()),
                ('new_mileage', models.PositiveIntegerField()),
                ('fuel_filled', models.DecimalField(decimal_places=2, max_digits=6)),
                ('issue_occurred', models.BooleanField(default=False)),
                ('issue_detail', models.TextField(blank=True, null=True)),
                ('trip_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='vehicles.triprequest')),
            ],
        ),
    ]
