# Generated by Django 5.2.1 on 2025-05-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0012_tripreport'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='destination',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
