# Generated by Django 5.2.1 on 2025-05-23 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0014_fueltype_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='triprequest',
            name='vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vehicles.vehicle'),
        ),
    ]
