# Generated by Django 5.2.1 on 2025-05-25 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0015_alter_triprequest_vehicle'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicle',
            name='mission_type',
        ),
    ]
