# Generated by Django 5.2.1 on 2025-05-26 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0016_remove_vehicle_mission_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='tripreport',
            name='old_mileage',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
