# Generated by Django 5.2.1 on 2025-05-26 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0017_tripreport_old_mileage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tripreport',
            name='fuel_filled',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
    ]
