# Generated by Django 5.2.1 on 2025-05-26 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0018_alter_tripreport_fuel_filled'),
    ]

    operations = [
        migrations.AddField(
            model_name='triprequest',
            name='fuel_used',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='triprequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('in_trip', 'In Trip'), ('reported', 'Reported'), ('trip_ended', 'Trip Ended'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
    ]
