# Generated by Django 5.2.1 on 2025-05-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0019_triprequest_fuel_used_alter_triprequest_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('cin', models.CharField(max_length=20, unique=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
