# Generated by Django 5.2.1 on 2025-05-27 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0021_alter_driver_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_going', models.DateField()),
                ('date_coming_back', models.DateField()),
                ('destination', models.CharField(max_length=255)),
                ('fuel_used', models.DecimalField(decimal_places=2, max_digits=6)),
                ('motif', models.TextField()),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.driver')),
                ('mission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.mission')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicles.vehicle')),
            ],
        ),
    ]
